import { motion, useScroll, useTransform } from 'framer-motion'
import { useRef, useState, useEffect } from 'react'

// Hero background — generated by Higgsfield (replace URL when ready)
const HERO_BG = 'https://d8j0ntlcm91z4.cloudfront.net/user_3Dh2N4HpfmHr3sqVUsWx08TjMB3/hf_20260520_150728_06f1619c-4b3c-49f4-bd6b-511027068f8b.png'
const APP_URL = 'https://veori-ai-main.up.railway.app'
const API_URL = APP_URL + '/api/billing'

function PulseDot() {
  return (
    <span style={{ position: 'relative', display: 'inline-block', width: 8, height: 8 }}>
      <span style={{ position: 'absolute', inset: 0, borderRadius: '50%', background: '#00C47B', animation: 'pulse-ring 1.8s ease-out infinite', transform: 'scale(1)', opacity: 0 }} />
      <span style={{ display: 'block', width: 8, height: 8, borderRadius: '50%', background: '#00C47B' }} />
    </span>
  )
}

function LiveMetric({ label, value, color = '#fff' }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
      <div style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 22, fontWeight: 600, color, letterSpacing: '-0.02em', lineHeight: 1 }}>{value}</div>
      <div style={{ fontSize: 10, fontWeight: 600, letterSpacing: '0.12em', textTransform: 'uppercase', color: 'rgba(255,255,255,0.40)' }}>{label}</div>
    </div>
  )
}

export default function Hero() {
  const ref = useRef(null)
  const { scrollYProgress } = useScroll({ target: ref, offset: ['start start', 'end start'] })
  const bgY   = useTransform(scrollYProgress, [0, 1], ['0%', '30%'])
  const textY = useTransform(scrollYProgress, [0, 1], ['0%', '18%'])
  const opacity = useTransform(scrollYProgress, [0, 0.7], [1, 0])

  const [name, setName]   = useState('')
  const [email, setEmail] = useState('')
  const [loading, setLoading] = useState(false)
  const [done, setDone]   = useState(false)

  // Animated spots countdown
  const [spots, setSpots] = useState(50)
  useEffect(() => {
    let current = 50; const target = 38
    const t = setInterval(() => {
      if (current > target) { current--; setSpots(current); } else clearInterval(t)
    }, 80)
    return () => clearInterval(t)
  }, [])

  async function handleSubmit(e) {
    e.preventDefault()
    if (!name.trim() || !email.includes('@')) return
    setLoading(true)
    try {
      const res = await fetch(`${API_URL}/checkout`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name, email, plan: 'founding' }),
      })
      const data = await res.json()
      if (data.url) { window.location.href = data.url; return }
    } catch {}
    setLoading(false)
    setDone(true)
  }

  const hasBg = HERO_BG !== '__HERO_IMAGE_URL__'

  return (
    <section ref={ref} style={{ position: 'relative', minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }}>

      {/* Background image with parallax */}
      <motion.div
        style={{ position: 'absolute', inset: '-10%', y: bgY, backgroundImage: hasBg ? `url(${HERO_BG})` : 'none', backgroundColor: hasBg ? 'transparent' : '#060E1A', backgroundSize: 'cover', backgroundPosition: 'center' }}
      />

      {/* If no image yet: cinematic dark gradient stand-in */}
      {!hasBg && (
        <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(ellipse 120% 80% at 60% 40%, #0A1E38 0%, #060E1A 70%)' }} />
      )}

      {/* Overlay gradient for readability */}
      <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to bottom, rgba(6,14,26,0.55) 0%, rgba(6,14,26,0.72) 60%, rgba(6,14,26,0.92) 100%)' }} />

      {/* Subtle grid over overlay */}
      <div className="grid-pattern" style={{ position: 'absolute', inset: 0, opacity: 0.6 }} />

      {/* Glow */}
      <div style={{ position: 'absolute', top: '10%', left: '50%', transform: 'translateX(-50%)', width: 800, height: 500, background: 'radial-gradient(ellipse at center, rgba(0,196,123,0.09) 0%, transparent 70%)', pointerEvents: 'none', animation: 'glow-breathe 4s ease-in-out infinite' }} />

      {/* Content */}
      <motion.div style={{ position: 'relative', zIndex: 10, y: textY, opacity, textAlign: 'center', padding: '140px 24px 80px', maxWidth: 1000, margin: '0 auto', width: '100%' }}>

        {/* Badge */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.2, ease: [0.22,1,0.36,1] }}
          style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: 'rgba(0,196,123,0.10)', border: '1px solid rgba(0,196,123,0.22)', borderRadius: 100, padding: '6px 16px', marginBottom: 36 }}
        >
          <PulseDot />
          <span style={{ fontSize: 12.5, fontWeight: 600, color: '#00C47B', letterSpacing: '0.01em' }}>Accepting first 50 founding operators</span>
        </motion.div>

        {/* Headline */}
        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.75, delay: 0.32, ease: [0.22,1,0.36,1] }}
          style={{ fontSize: 'clamp(44px,7vw,80px)', fontWeight: 900, letterSpacing: '-0.04em', lineHeight: 1.04, marginBottom: 22 }}
        >
          Your AI VA That<br />
          <span className="text-shimmer">Never Stops Calling</span>
        </motion.h1>

        {/* Sub */}
        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.75, delay: 0.42, ease: [0.22,1,0.36,1] }}
          style={{ fontSize: 'clamp(16px,1.8vw,19px)', color: 'rgba(255,255,255,0.72)', lineHeight: 1.68, maxWidth: 600, margin: '0 auto 48px' }}
        >
          VEORI calls your leads, qualifies sellers, and makes offers automatically. 24/7. No sick days, no training, no inconsistency.
          Beta founding operators lock in <strong style={{ color: '#C9A84C' }}>$197/month forever.</strong>
        </motion.p>

        {/* Form */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.75, delay: 0.52, ease: [0.22,1,0.36,1] }}
          style={{ maxWidth: 480, margin: '0 auto' }}
        >
          {!done ? (
            <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              <input
                type="text" placeholder="Your name" value={name} onChange={e => setName(e.target.value)} required
                style={{ width: '100%', padding: '13px 18px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.10)', borderRadius: 10, color: '#fff', fontSize: 15, fontFamily: 'Inter,sans-serif', outline: 'none' }}
                onFocus={e => e.target.style.borderColor = 'rgba(0,196,123,0.4)'}
                onBlur={e => e.target.style.borderColor = 'rgba(255,255,255,0.10)'}
              />
              <input
                type="email" placeholder="Your email address" value={email} onChange={e => setEmail(e.target.value)} required
                style={{ width: '100%', padding: '13px 18px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.10)', borderRadius: 10, color: '#fff', fontSize: 15, fontFamily: 'Inter,sans-serif', outline: 'none' }}
                onFocus={e => e.target.style.borderColor = 'rgba(0,196,123,0.4)'}
                onBlur={e => e.target.style.borderColor = 'rgba(255,255,255,0.10)'}
              />
              <button
                type="submit" disabled={loading}
                style={{ width: '100%', padding: '15px', background: loading ? 'rgba(0,196,123,0.7)' : '#00C47B', color: '#000', fontSize: 16, fontWeight: 800, border: 'none', borderRadius: 10, cursor: loading ? 'wait' : 'pointer', fontFamily: 'Inter,sans-serif', letterSpacing: '-0.01em', transition: 'all 0.2s' }}
                onMouseEnter={e => { if (!loading) { e.target.style.background = '#00d986'; e.target.style.transform = 'translateY(-1px)'; e.target.style.boxShadow = '0 12px 36px rgba(0,196,123,0.40)'; }}}
                onMouseLeave={e => { e.target.style.background = '#00C47B'; e.target.style.transform = ''; e.target.style.boxShadow = ''; }}
              >
                {loading ? 'Redirecting to checkout...' : `Join Beta — $197/mo Locked Forever →`}
              </button>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, fontSize: 12.5, color: 'rgba(255,255,255,0.35)', marginTop: 2 }}>
                <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#C9A84C', display: 'inline-block' }} />
                <span><strong style={{ color: 'rgba(255,255,255,0.50)' }}>{spots}</strong> founding spots remaining of 50</span>
                <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#C9A84C', display: 'inline-block' }} />
              </div>
            </form>
          ) : (
            <div style={{ background: 'rgba(0,196,123,0.10)', border: '1px solid rgba(0,196,123,0.28)', borderRadius: 14, padding: '24px 28px', fontSize: 16, color: '#00C47B', fontWeight: 600 }}>
              You're in. We'll reach out within 24 hours to get you set up.
            </div>
          )}
        </motion.div>

        {/* Live metrics strip */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1, delay: 0.9 }}
          style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 40, flexWrap: 'wrap', marginTop: 56, padding: '20px 32px', borderRadius: 14, background: 'rgba(10,21,38,0.70)', border: '1px solid rgba(255,255,255,0.06)', backdropFilter: 'blur(12px)', maxWidth: 640, margin: '56px auto 0' }}
        >
          <LiveMetric label="Calls / day" value="500" color="#00C47B" />
          <div style={{ width: 1, height: 36, background: 'rgba(255,255,255,0.06)' }} />
          <LiveMetric label="Contract time" value="4 min" />
          <div style={{ width: 1, height: 36, background: 'rgba(255,255,255,0.06)' }} />
          <LiveMetric label="Follow-up window" value="12 mo" />
          <div style={{ width: 1, height: 36, background: 'rgba(255,255,255,0.06)' }} />
          <LiveMetric label="Human required" value="Zero" />
        </motion.div>
      </motion.div>

      {/* Scroll indicator */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 1.4, duration: 0.8 }}
        style={{ position: 'absolute', bottom: 32, left: '50%', transform: 'translateX(-50%)', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6, animation: 'float 2.5s ease-in-out infinite' }}
      >
        <div style={{ fontSize: 10.5, fontWeight: 600, letterSpacing: '0.15em', textTransform: 'uppercase', color: 'rgba(255,255,255,0.28)' }}>Scroll</div>
        <div style={{ width: 1, height: 32, background: 'linear-gradient(to bottom, rgba(0,196,123,0.6), transparent)' }} />
      </motion.div>
    </section>
  )
}
