/**
 * Dropbox Sign (HelloSign) e-signing service.
 * White-label — zero Dropbox branding in UI.
 * All signing happens inside the Veori UI.
 */

const hellosign = require('hellosign-sdk');

let client = null;

function getClient() {
  if (!client) {
    client = new hellosign({ key: process.env.DROPBOX_SIGN_API_KEY });
  }
  return client;
}

const CONTRACT_FOOTER = '\n\nThis document was generated by Veori AI and does not constitute legal advice. Consult a licensed real estate attorney in your state before signing.';

// ─── Create a signature request ───────────────────────────────────────────────
async function createSignatureRequest({ contractId, contractType, pdfUrl, signers, title, subject, message }) {
  const hs = getClient();

  const opts = {
    test_mode: process.env.NODE_ENV !== 'production' ? 1 : 0,
    title: title || `Veori AI — ${contractType} Agreement`,
    subject: subject || `Please review and sign your ${contractType} agreement`,
    message: message || `Your real estate contract is ready for your review and signature. ${CONTRACT_FOOTER.trim()}`,
    signers: signers.map((s, i) => ({
      email_address: s.email,
      name: s.name,
      order: i,
    })),
    file_url: pdfUrl ? [pdfUrl] : undefined,
    metadata: { contract_id: contractId, contract_type: contractType, platform: 'veori-ai' },
    allow_decline: true,
    use_text_tags: false,
  };

  const res = await hs.signatureRequest.send(opts);
  return res.signature_request;
}

// ─── Create embedded signing session (renders in Veori UI) ───────────────────
async function createEmbeddedSigningUrl(signatureRequestId, signatureId) {
  const hs = getClient();

  const res = await hs.embedded.getSignUrl(signatureId);
  return {
    sign_url: res.embedded.sign_url,
    expires_at: res.embedded.expires_at,
  };
}

// ─── Get signature request status ────────────────────────────────────────────
async function getSignatureRequestStatus(signatureRequestId) {
  const hs = getClient();
  const res = await hs.signatureRequest.get(signatureRequestId);
  return res.signature_request;
}

// ─── Download signed document ─────────────────────────────────────────────────
async function downloadSignedDocument(signatureRequestId) {
  const hs = getClient();
  const res = await hs.signatureRequest.download(signatureRequestId, {
    file_type: 'pdf',
    get_url: true,
  });
  return res;
}

// ─── Cancel a signature request ───────────────────────────────────────────────
async function cancelSignatureRequest(signatureRequestId) {
  const hs = getClient();
  return hs.signatureRequest.cancel(signatureRequestId);
}

// ─── Map Dropbox Sign status to our status ───────────────────────────────────
function mapSigningStatus(dsStatus) {
  const map = {
    'awaiting_signature': 'sent',
    'signed':             'fully_signed',
    'declined':           'declined',
    'out_for_signature':  'sent',
    'error':              'error',
  };
  return map[dsStatus] || 'unsigned';
}

module.exports = {
  createSignatureRequest,
  createEmbeddedSigningUrl,
  getSignatureRequestStatus,
  downloadSignedDocument,
  cancelSignatureRequest,
  mapSigningStatus,
  CONTRACT_FOOTER,
};
