/**
 * Dual AI Service — routes tasks to the right model:
 * - GPT-4o:           lead qualification, conversation extraction, live call coaching
 * - Claude Sonnet 4.6: deal analysis, analytics insights, deal brief, contract language, market trends
 */

const Anthropic = require('@anthropic-ai/sdk');
const OpenAI    = require('openai');

let anthropicClient = null;
let openaiClient    = null;

function getAnthropic() {
  if (!anthropicClient) {
    anthropicClient = new Anthropic({
      apiKey: process.env.ANTHROPIC_API_KEY,
      timeout: 55000,   // 55s — just under Railway's 60s request timeout
      maxRetries: 2,
    });
  }
  return anthropicClient;
}

function getOpenAI() {
  if (!openaiClient) {
    openaiClient = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  }
  return openaiClient;
}

const AI_DISCLAIMER = '\n\n⚠️ This analysis was generated by AI and is not financial or legal advice. Verify all figures before making any offer.';

// ─── GPT-4o: Lead qualification scoring ──────────────────────────────────────
async function qualifyLead({ name, phone, propertyAddress, conversationHistory, motivationType }) {
  const openai = getOpenAI();
  const messages = [
    {
      role: 'system',
      content: `You are an expert real estate wholesale acquisitions AI. Analyze this seller conversation and score their motivation 0-100.

Scoring criteria:
- 80-100: Highly motivated — urgent timeline, financial pressure, distressed property
- 60-79: Motivated — ready to sell, open to offers
- 40-59: Somewhat motivated — considering selling
- 0-39: Low motivation — not serious or testing the market

Return ONLY valid JSON:
{
  "motivation_score": <number 0-100>,
  "motivation_factors": ["factor1", "factor2"],
  "recommended_action": "escalate_to_pipeline|continue_nurturing|archive",
  "seller_personality": "analytical|emotional|skeptical|motivated|resistant",
  "key_objections": ["objection1"],
  "estimated_timeline": "immediate|30days|60days|90days|unknown",
  "confidence": <number 0-100>
}`,
    },
    {
      role: 'user',
      content: `Seller: ${name}\nPhone: ${phone}\nProperty: ${propertyAddress}\nMotivation type: ${motivationType}\n\nConversation:\n${conversationHistory || 'No conversation yet — initial qualification.'}`,
    },
  ];

  const res = await openai.chat.completions.create({
    model: 'gpt-4o',
    messages,
    max_tokens: 400,
    temperature: 0.3,
    response_format: { type: 'json_object' },
  });

  return JSON.parse(res.choices[0].message.content);
}

// ─── GPT-4o: Extract deal terms from SMS conversation ─────────────────────────
async function extractDealTerms(conversationText) {
  const openai = getOpenAI();
  const res = await openai.chat.completions.create({
    model: 'gpt-4o',
    messages: [
      {
        role: 'system',
        content: `Extract real estate deal terms from this conversation. Return ONLY valid JSON:
{
  "offer_price": <number or null>,
  "contingencies": ["inspection", "financing", "appraisal"],
  "closing_date": "<ISO date string or null>",
  "special_terms": "<string or null>",
  "seller_asking_price": <number or null>,
  "requested_call": <boolean>,
  "call_requested_time": "<string or null>",
  "call_requested_timezone": "<string or null>",
  "next_action": "voice_call|send_offer|send_contract|schedule_followup|none"
}`,
      },
      { role: 'user', content: conversationText },
    ],
    max_tokens: 300,
    temperature: 0.1,
    response_format: { type: 'json_object' },
  });

  return JSON.parse(res.choices[0].message.content);
}

// ─── GPT-4o: Parse requested call time from SMS ───────────────────────────────
async function parseCallTime(message) {
  const openai = getOpenAI();
  const res = await openai.chat.completions.create({
    model: 'gpt-4o',
    messages: [
      {
        role: 'system',
        content: `Extract the requested call time from this message. Today is ${new Date().toISOString()}. Return ONLY valid JSON:
{
  "requested_time": "<ISO 8601 UTC datetime or null>",
  "timezone": "<IANA timezone string or null>",
  "is_explicit_call_request": <boolean>,
  "confidence": <number 0-100>
}`,
      },
      { role: 'user', content: message },
    ],
    max_tokens: 150,
    temperature: 0.1,
    response_format: { type: 'json_object' },
  });

  return JSON.parse(res.choices[0].message.content);
}

// ─── GPT-4o: Post-conversation insight extraction ────────────────────────────
async function extractConversationInsights({ conversationText, outcome }) {
  const openai = getOpenAI();
  const res = await openai.chat.completions.create({
    model: 'gpt-4o',
    messages: [
      {
        role: 'system',
        content: `Analyze this real estate seller/buyer conversation and extract learning data. Return ONLY valid JSON:
{
  "objections_raised": [{"text": "...", "category": "price|timing|condition|trust|other"}],
  "successful_language": ["phrase1", "phrase2"],
  "disengagement_triggers": ["trigger1"],
  "sentiment_start": <number -100 to 100>,
  "sentiment_end": <number -100 to 100>,
  "sentiment_inflection_points": [{"at_message": <number>, "shift": "positive|negative"}],
  "outcome": "${outcome}"
}`,
      },
      { role: 'user', content: conversationText },
    ],
    max_tokens: 500,
    temperature: 0.2,
    response_format: { type: 'json_object' },
  });

  return JSON.parse(res.choices[0].message.content);
}

// ─── Claude Sonnet 4.6: Deal analysis ────────────────────────────────────────
async function analyzeDeal({ propertyAddress, arv, repairCosts, offerPrice, state, sellerMotivationScore, daysOnMarket, buyerPoolDepth }) {
  const anthropic = getAnthropic();
  const mao = (arv * 0.70) - repairCosts;
  const assignmentFeeEstimate = arv * 0.05;

  const msg = await anthropic.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 600,
    messages: [{
      role: 'user',
      content: `Analyze this real estate wholesale deal and return ONLY valid JSON:

Property: ${propertyAddress}
State: ${state}
ARV: $${arv?.toLocaleString()}
Repair Costs: $${repairCosts?.toLocaleString()}
MAO (70% rule): $${mao?.toLocaleString()}
Offer Price: $${offerPrice?.toLocaleString()}
Seller Motivation Score: ${sellerMotivationScore}/100
Days on Market: ${daysOnMarket || 'unknown'}
Buyer Pool Depth: ${buyerPoolDepth || 'unknown'}

Return JSON:
{
  "risk_score": <number 1-10, where 1=low risk, 10=high risk>,
  "risk_factors": ["factor1", "factor2"],
  "assignment_fee_range": {"min": <number>, "max": <number>},
  "offer_assessment": "above_mao|at_mao|below_mao|significantly_below_mao",
  "offer_warning": "<string or null>",
  "scenarios": {
    "conservative": {"profit": <number>, "probability": <number 0-100>},
    "moderate": {"profit": <number>, "probability": <number 0-100>},
    "aggressive": {"profit": <number>, "probability": <number 0-100>}
  },
  "recommendation": "<2-sentence recommendation>",
  "deal_velocity_estimate_days": <number>
}`,
    }],
  });

  const result = JSON.parse(msg.content[0].text);
  result._disclaimer = AI_DISCLAIMER;
  return result;
}

// ─── Claude Sonnet 4.6: Smart Deal Brief ─────────────────────────────────────
async function generateDealBrief({ deal, lastAiAction, sellerName, nextRecommendedStep }) {
  const anthropic = getAnthropic();

  const msg = await anthropic.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 400,
    messages: [{
      role: 'user',
      content: `Generate a 5-sentence deal brief for a real estate operator. Be concise and direct. No fluff.

Deal data:
- Property: ${deal.property_address}, ${deal.state}
- Stage: ${deal.stage} (since: ${deal.stage_changed_at ? new Date(deal.stage_changed_at).toLocaleDateString() : 'unknown'})
- Seller: ${sellerName || 'Unknown'}
- Motivation Score: ${deal.motivation_score || 'N/A'}/100
- Velocity Score: ${deal.deal_velocity_score || 'N/A'}%
- Last AI Action: ${lastAiAction || 'None recorded'}
- Risk Level: ${deal.risk_level || 'medium'}
- Offer: $${deal.offer_price?.toLocaleString() || 'None'} / MAO: $${deal.mao?.toLocaleString() || 'N/A'}

Write exactly 5 sentences:
1. Current stage and how long it has been there
2. Seller motivation score and what is driving it
3. Last AI action taken and when
4. Next recommended step
5. Risk level and any flags`,
    }],
  });

  return {
    brief: msg.content[0].text,
    disclaimer: 'This brief was generated by AI and is for informational purposes only.',
  };
}

// ─── Claude Sonnet 4.6: Analytics AI Insights ────────────────────────────────
async function generateAnalyticsInsights({ kpis, topStates, recentDeals, marketAlerts }) {
  const anthropic = getAnthropic();

  const msg = await anthropic.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 500,
    messages: [{
      role: 'user',
      content: `Generate 5-7 AI insights for a real estate wholesale operator dashboard. Use real data only. Each insight should start with an emoji. Be specific with numbers.

Data:
${JSON.stringify({ kpis, topStates, recentDeals: recentDeals?.slice(0, 10), marketAlerts }, null, 2)}

Format: Return a JSON array of insight strings. Each string starts with an emoji.
Example: ["🔥 West Texas closed 3 deals in 14 days avg", "⚠️ 2 deals have title overdue"]

Return ONLY valid JSON array.`,
    }],
  });

  try {
    return JSON.parse(msg.content[0].text);
  } catch {
    return [msg.content[0].text];
  }
}

// ─── Claude Sonnet 4.6: Contract compliance language ─────────────────────────
async function generateComplianceDisclosure({ state, dealType }) {
  const anthropic = getAnthropic();

  const msg = await anthropic.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 300,
    messages: [{
      role: 'user',
      content: `Generate the required disclosure language for a real estate wholesale ${dealType} contract in ${state}.

Keep it concise (under 100 words). Include only factual legal disclosure text, not advice.
Always end with: "This document was generated by Veori AI and does not constitute legal advice. Consult a licensed real estate attorney in ${state} before signing."`,
    }],
  });

  return msg.content[0].text;
}

// ─── Claude Sonnet 4.6: Market trend detection ───────────────────────────────
async function detectMarketTrends(marketData) {
  const anthropic = getAnthropic();

  const msg = await anthropic.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 400,
    messages: [{
      role: 'user',
      content: `Analyze this real estate market data and identify significant trends. Return ONLY valid JSON:

${JSON.stringify(marketData, null, 2)}

{
  "alerts": [
    {
      "market": "<state/county/metro>",
      "trend": "rising|falling|stable",
      "percentage_change": <number>,
      "alert_message": "<string starting with emoji>",
      "severity": "high|medium|low"
    }
  ],
  "summary": "<2 sentence overall market summary>"
}`,
    }],
  });

  return JSON.parse(msg.content[0].text);
}

module.exports = {
  qualifyLead,
  extractDealTerms,
  parseCallTime,
  extractConversationInsights,
  analyzeDeal,
  generateDealBrief,
  generateAnalyticsInsights,
  generateComplianceDisclosure,
  detectMarketTrends,
};
